### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-data-sampler#7]
The aim is to move away from torch.datapipes which is in ocf_datapipes. 
We want to build a pipline for pvnet which would be ready for training and ready to deployed in the app

Things we will keep the same
- config
- BatchML strcuture

Things to do
- [x] #8
- [ ] Tidy up and refactor
- [x] Use Import ocf_datapipe, until its ready
- [x] CI, pytest
- [x] CI release
- [x] Update pvnet_app to use it - https://github.com/openclimatefix/uk-pvnet-app/pull/118
- [ ] Minimum documentation, example of batch in torch.dataloader
- [x] Make script than can save batches
- [x] Make sure pvnet can be trained
- [ ] Review, Sukh, Peter, Alex
- [x] Retrain PVnet to use ocf_datapipes
- [x] update pvnet to not use ocf_datapipes,

For later
- [x] remove ocf_datapipes from this repo
- [ ] Add pv functions
- [ ] https://github.com/openclimatefix/PVNet-summation/issues/26
- [ ] pvnet_sites, windnet
- [ ] refactor function, try for now to keep function how they are.

**Comment by dfulu** [comment]
@peterdudfield I'm going to close this. I think its deprecated by #98
