### ISSUE TITLE
2025 ocf-data-sampler - let's make it happen

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-data-sampler#98]
Copying over from ML-notes

Thank you @Sukh-P @dfulu @AUdaltsova @felix-e-h-p for all your work on this so far

Here are the tasks to do, in order to fully move over from ocf-datapipes to ocf-data-sampler

Phase 1
- [x] Update example configs - [PR](https://github.com/openclimatefix/PVNet/pull/292) 
- [x] Satellite scaling openclimatefix/ocf-data-sampler#87
- [x] openclimatefix/ocf-data-sampler#82 
- [x] Can save Site samples using ocf-data-sampler/PVnet script [PR](https://github.com/openclimatefix/PVNet/pull/290) 
- [x] Logic going from netcdfs to tensor batches (Sukh start, maybe review Peter)  - sit in ocf-data-sampler  - https://github.com/openclimatefix/PVNet/issues/301
- [x] Make separate torch_dataset to load premade netcdf samples - https://github.com/openclimatefix/PVNet/issues/301
- [x] Test training for site level dataset 
- [x] https://github.com/openclimatefix/PVNet/issues/305
- [x] https://github.com/openclimatefix/ocf-data-sampler/issues/77
- [x] https://github.com/openclimatefix/ocf-data-sampler/issues/100
- [x] https://github.com/openclimatefix/ocf-data-sampler/issues/103
- [x] Refactor PVNet after the name change from "batch" to "samples"
- [x] forecast apps after the name change from "batch" to "samples"
- [x] Bug: https://github.com/openclimatefix/PVNet/issues/304

Phase 2:
- [x] Train a site level model, and compare with models. This could be an India model as its ready to go.  (Sukh)
- [x] Re train UK GSP PVnet model, with satellite scaling. @dfulu to do this later this month by testing end to end
- [x] openclimatefix/PVNet#308
- [ ] https://github.com/openclimatefix/PVNet/issues/313
- [x]  Add torch dataset for training summational model (James/Felix), some work done already by James but using an older version of ocf-data-sampler 
- [x] Train the summation models (both intraday/DA) with ocf-data-sampler (James/Felix) 
 - [x] Simplify sample/batch interface (with a Sample/batch class) so there is a common interface used between all samples - openclimatefix/ocf-data-sampler#71 
 - [x] Remove ocf_datapipes dependencies in PVNet dev data-sampler branch, may need to migrate some code from ocf_datapipes to data-sampler @felix-e-h-p 
 - [x] openclimatefix/PVNet#310
 - [x] Merge PVNet dev to main
- [x] Pvnet Da: Use data-sampler in new projects going forward - https://github.com/openclimatefix/PVNet/issues/289
- [x] https://github.com/openclimatefix/uk-pvnet-app/issues/168
- [x] GDM: Use data-sampler in new project
- [ ] Fully move uk-pvnet-app over to ocf-data-sampler - https://github.com/openclimatefix/uk-pvnet-app/issues/116
- [ ] openclimatefix/india-forecast-app#164

Not do/ do later: Training like to like batches with ocf-data-sampler and ocf-datapipes

Future:
 - Add more features that were in ocf_datapipes, support for different NWPs etc
- Save in zipped folder with separate netcdfs per input
- aswell as lots of other issues
- visualise batches in internal dashboard

**Comment by Sukh-P** [comment]
Closing this meta issue since the majority are done and separate issues are being created for any outstanding work
